import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import"./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Abdelrahman_CV",
  description: "Generated by create next app,it,s a cv for abdelrahman gamal",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en,ar">
      <head>
        <script
        async
        src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8865069421209568"
        crossOrigin="anonymous" // Added crossOrigin for better practice
      ></script>
        <link rel="icon" href="./favicon.ico"></link>
      </head>
      <body className={ `${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
